name: infrastructure-deploy
on:
  push:
    branches:
      - master

jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT