name: comment-cicd
on:
  issue_comment:
    types: [created]

jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - env:
          PR_URL: ${{ github.event.issue.url }}
        run: |
          echo $PR_URL
      
      - name: GET_PR_URL
        uses: octokit/request-action@v2.x
        id: get_pr_url
        with:
          route: GET ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_GITHUB_TOKEN  }}

      - name: branch
        id: bracncl
        env: 
          BRANCH: ${{ steps.create_check_run.outputs.data }}
        run: | 
          echo "$BRANCH"
