name: comment-cicd
on:
  pull_request_review_comment:
    types: [ created ]
  issue_comment:
    types: [created]

jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT