name: comment-cicd
on:
  issue_comment:
    types: [created]

jobs:
  event-details:
    if: ${{ github.event.issue.pull_request }}
    if: ${{ contains(github.event.comment.body, '[deploy-infra]') }}
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT 
      - name: GET_PR_URL
        uses: octokit/request-action@v2.x
        id: get_pr_url
        with:
          route: GET ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_GITHUB_TOKEN }}

      - name: branch
        id: bracncl
        env: 
          BRANCH: ${{ fromJson(steps.get_pr_url.outputs.data).head.ref }}
        run: | 
          echo "$BRANCH"

      - name: comment_print
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          echo "$COMMENT"