name: infrastructure-preview
on:
  pull_request:
    branches:
      - master

jobs:
  event-details:
    if: ${{ startsWith(github.event.pull_request.head.ref, 'qa') || startsWith(github.event.pull_request.head.ref, 'stg') || startsWith(github.event.pull_request.head.ref, 'prd')  }}
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT